[project]
name = "fitme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "aiohttp>=3.12.15",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
]
